-- Limpa todas as tabelas (ordem filhos -> pai); com FKs ON DELETE CASCADE, basta deletar o pai:
DELETE FROM PROJETO_TECNOLOGIA;
DELETE FROM EXPERIENCIA_REALIZACAO;
DELETE FROM EXPERIENCIA_TECNOLOGIA;
DELETE FROM ANEXO;
DELETE FROM REFERENCIA_PROFISSIONAL;
DELETE FROM CONQUISTA;
DELETE FROM PROJETO;
DELETE FROM IDIOMA;
DELETE FROM CURSO;
DELETE FROM CERTIFICACAO;
DELETE FROM SOFT_SKILL;
DELETE FROM HABILIDADE;
DELETE FROM EXPERIENCIA;
DELETE FROM FORMACAO;
DELETE FROM CANDIDATO;

COMMIT;