-- =========================================================
-- SCHEMA TALENTCORE (ORACLE) - DDL COMPLETA
-- =========================================================

-- Drop em ordem filhos -> pai (opcional, dev)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROJETO_TECNOLOGIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXPERIENCIA_REALIZACAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXPERIENCIA_TECNOLOGIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ANEXO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REFERENCIA_PROFISSIONAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONQUISTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROJETO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE IDIOMA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CURSO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CERTIFICACAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SOFT_SKILL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HABILIDADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXPERIENCIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FORMACAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CANDIDATO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =======================
-- Tabela raiz: CANDIDATO
-- =======================
CREATE TABLE CANDIDATO (
  ID                  VARCHAR2(36)   PRIMARY KEY,
  NOME_COMPLETO       VARCHAR2(200)  NOT NULL,
  DATA_NASCIMENTO     DATE           NULL,
  TELEFONE            VARCHAR2(50),
  EMAIL               VARCHAR2(200),
  LOGRADOURO          VARCHAR2(200),
  NUMERO              VARCHAR2(20),
  COMPLEMENTO         VARCHAR2(100),
  BAIRRO              VARCHAR2(100),
  CIDADE              VARCHAR2(100),
  ESTADO              VARCHAR2(50),
  PAIS                VARCHAR2(100),
  CEP                 VARCHAR2(20),
  LINKEDIN            VARCHAR2(300),
  GITHUB              VARCHAR2(300),
  PORTFOLIO           VARCHAR2(300),
  NACIONALIDADE       VARCHAR2(80),
  ESTADO_CIVIL        VARCHAR2(50),
  RESUMO_PROFISSIONAL CLOB,
  PRETENSAO_SALARIAL  VARCHAR2(50),
  ACEITA_VIAGENS      CHAR(1) CHECK (ACEITA_VIAGENS IN ('S','N')),
  ACEITA_MUDANCA      CHAR(1) CHECK (ACEITA_MUDANCA IN ('S','N')),
  HORARIOS            VARCHAR2(255)
);

CREATE UNIQUE INDEX UX_CANDIDATO_EMAIL ON CANDIDATO (UPPER(EMAIL));
CREATE INDEX IX_CAND_CIDADE ON CANDIDATO (UPPER(CIDADE));
CREATE INDEX IX_CAND_ESTADO ON CANDIDATO (UPPER(ESTADO));

-- ==========
-- FORMACAO
-- ==========
CREATE TABLE FORMACAO (
  ID             VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID   VARCHAR2(36) NOT NULL,
  INSTITUICAO    VARCHAR2(200),
  CURSO          VARCHAR2(200),
  NIVEL          VARCHAR2(30),
  DATA_INICIO    DATE,
  DATA_FIM       DATE,
  DESCRICAO      VARCHAR2(1000),
  CONSTRAINT FK_FORM_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

-- ==========
-- EXPERIENCIA
-- ==========
CREATE TABLE EXPERIENCIA (
  ID               VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID     VARCHAR2(36) NOT NULL,
  EMPRESA          VARCHAR2(200),
  CARGO            VARCHAR2(200),
  TIPO             VARCHAR2(30),    -- CLT/PJ/ESTAGIO/FREELANCE
  DATA_INICIO      DATE,
  DATA_FIM         DATE,
  DESCRICAO_ATIV   VARCHAR2(2000),
  CONSTRAINT FK_EXP_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

CREATE TABLE EXPERIENCIA_TECNOLOGIA (
  EXPERIENCIA_ID VARCHAR2(36) NOT NULL,
  TECNOLOGIA     VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_EXP_TEC PRIMARY KEY (EXPERIENCIA_ID, TECNOLOGIA),
  CONSTRAINT FK_EXP_TEC_EXP FOREIGN KEY (EXPERIENCIA_ID) REFERENCES EXPERIENCIA(ID) ON DELETE CASCADE
);

CREATE TABLE EXPERIENCIA_REALIZACAO (
  ID             VARCHAR2(36) PRIMARY KEY,
  EXPERIENCIA_ID VARCHAR2(36) NOT NULL,
  DESCRICAO      VARCHAR2(1000),
  CONSTRAINT FK_EXP_REAL_EXP FOREIGN KEY (EXPERIENCIA_ID) REFERENCES EXPERIENCIA(ID) ON DELETE CASCADE
);

CREATE INDEX IX_EXPTEC_TEC ON EXPERIENCIA_TECNOLOGIA (UPPER(TECNOLOGIA));

-- ==========
-- HABILIDADE / SOFT_SKILL
-- ==========
CREATE TABLE HABILIDADE (
  ID            VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID  VARCHAR2(36) NOT NULL,
  NOME          VARCHAR2(150),
  CATEGORIA     VARCHAR2(100),
  NIVEL         VARCHAR2(30), -- BASICO/INTERMEDIARIO/AVANCADO/EXPERT
  CONSTRAINT FK_HAB_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

CREATE TABLE SOFT_SKILL (
  ID            VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID  VARCHAR2(36) NOT NULL,
  NOME          VARCHAR2(150),
  NIVEL         VARCHAR2(30),
  CONSTRAINT FK_SOFT_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

-- ==========
-- CERTIFICACAO / CURSO
-- ==========
CREATE TABLE CERTIFICACAO (
  ID                 VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID       VARCHAR2(36) NOT NULL,
  NOME               VARCHAR2(200),
  INSTITUICAO        VARCHAR2(200),
  DATA_OBTENCAO      DATE,
  DATA_EXPIRACAO     DATE,
  NUMERO_CREDENCIAL  VARCHAR2(100),
  URL_CREDENCIAL     VARCHAR2(300),
  CONSTRAINT FK_CERT_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

CREATE TABLE CURSO (
  ID             VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID   VARCHAR2(36) NOT NULL,
  NOME           VARCHAR2(200),
  INSTITUICAO    VARCHAR2(200),
  CARGA_HORARIA  NUMBER(6),
  DATA_CONCLUSAO DATE,
  CONSTRAINT FK_CURSO_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

-- ==========
-- IDIOMA
-- ==========
CREATE TABLE IDIOMA (
  ID            VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID  VARCHAR2(36) NOT NULL,
  IDIOMA        VARCHAR2(50),
  NIVEL         VARCHAR2(30), -- BASICO/INTERMEDIARIO/AVANCADO/FLUENTE/NATIVO
  CONSTRAINT FK_IDIOMA_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

CREATE INDEX IX_IDIOMA_IDIOMA ON IDIOMA (UPPER(IDIOMA));
CREATE INDEX IX_IDIOMA_NIVEL  ON IDIOMA (UPPER(NIVEL));

-- ==========
-- PROJETO + TECNOLOGIA
-- ==========
CREATE TABLE PROJETO (
  ID            VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID  VARCHAR2(36) NOT NULL,
  NOME          VARCHAR2(200),
  DESCRICAO     VARCHAR2(2000),
  DATA_INICIO   DATE,
  DATA_FIM      DATE,
  CONSTRAINT FK_PROJ_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

CREATE TABLE PROJETO_TECNOLOGIA (
  PROJETO_ID  VARCHAR2(36) NOT NULL,
  TECNOLOGIA  VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_PROJ_TEC PRIMARY KEY (PROJETO_ID, TECNOLOGIA),
  CONSTRAINT FK_PROJ_TEC_PROJ FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO(ID) ON DELETE CASCADE
);

CREATE INDEX IX_PROJTEC_TEC ON PROJETO_TECNOLOGIA (UPPER(TECNOLOGIA));

-- ==========
-- CONQUISTA / REFERENCIA / ANEXO
-- ==========
CREATE TABLE CONQUISTA (
  ID            VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID  VARCHAR2(36) NOT NULL,
  TITULO        VARCHAR2(200),
  ORGANIZACAO   VARCHAR2(200),
  ANO           NUMBER(4),
  DESCRICAO     VARCHAR2(1000),
  CONSTRAINT FK_CONQ_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

CREATE TABLE REFERENCIA_PROFISSIONAL (
  ID            VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID  VARCHAR2(36) NOT NULL,
  NOME          VARCHAR2(200),
  CARGO         VARCHAR2(150),
  EMPRESA       VARCHAR2(200),
  TELEFONE      VARCHAR2(50),
  EMAIL         VARCHAR2(200),
  CONSTRAINT FK_REF_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);

CREATE TABLE ANEXO (
  ID            VARCHAR2(36) PRIMARY KEY,
  CANDIDATO_ID  VARCHAR2(36) NOT NULL,
  TIPO          VARCHAR2(30),
  URL_ARQUIVO   VARCHAR2(400),
  DATA_UPLOAD   TIMESTAMP,
  CONSTRAINT FK_ANEXO_CAND FOREIGN KEY (CANDIDATO_ID) REFERENCES CANDIDATO(ID) ON DELETE CASCADE
);